import { useForm, usePage } from '@inertiajs/react';
import { useState } from 'react';
import AppLayout from '@/Layouts/AppLayout';
import { EmptyState, Initials, PageHero, Panel, SecretariatStyles, StatCard, StatusPill } from '../Shared';

function ReceiptForm({ plan }) {
    const form = useForm({ receipt_status: plan.receipt_status ?? 'pending', receipt_remarks: plan.receipt_remarks ?? '' });
    return <form onSubmit={(event) => { event.preventDefault(); form.patch(`/secretariat/lap-submissions/${plan.id}`, { preserveScroll: true }); }} className="sec-form" style={{ marginTop: '.75rem', paddingTop: '.75rem', borderTop: '1px dashed var(--admin-border-strong)' }}><div className="sec-field"><label>Receipt decision</label><select value={form.data.receipt_status} onChange={(event) => form.setData('receipt_status', event.target.value)}><option value="pending">Pending review</option><option value="received">Mark as received</option><option value="returned">Return for revision</option></select></div><div className="sec-field"><label>Secretariat remarks</label><textarea rows="3" value={form.data.receipt_remarks} onChange={(event) => form.setData('receipt_remarks', event.target.value)} placeholder="Receipt confirmation or revision notes" /></div><div className="sec-field full"><button className="sec-button" disabled={form.processing}><i className="bi bi-journal-check" />{form.processing ? 'Saving...' : 'Save receipt status'}</button></div></form>;
}

export default function Index({ plans }) {
    const { props } = usePage();
    const [expanded, setExpanded] = useState(null);
    const tone = (status) => status === 'received' ? 'success' : status === 'returned' ? 'danger' : 'warning';
    return <AppLayout title="LAP Submissions" description="Secretariat / Employee Learning Action Plans"><div className="sec-page"><PageHero kicker="POST-TRAINING DOCUMENT CONTROL" title="Receive the evidence of learning transfer." description="Review employee Learning Action Plans, record receipt confirmation, and return incomplete submissions with clear Secretariat remarks." href="/secretariat/reports" action="View terminal reports" icon="bi-file-earmark-bar-graph" />{props?.flash?.success && <div className="sec-success"><i className="bi bi-check-circle-fill" />{props.flash.success}</div>}<section className="sec-stats"><StatCard label="All LAP" value={(plans ?? []).length} icon="bi-journals" /><StatCard label="Pending Receipt" value={(plans ?? []).filter((item) => item.receipt_status === 'pending').length} icon="bi-hourglass" color="#facc15" /><StatCard label="Received" value={(plans ?? []).filter((item) => item.receipt_status === 'received').length} icon="bi-check2-circle" color="#34d399" /><StatCard label="Returned" value={(plans ?? []).filter((item) => item.receipt_status === 'returned').length} icon="bi-arrow-counterclockwise" color="#f87171" /></section><Panel title="Employee Learning Action Plans" subtitle="Actual post-training LAP submissions"><div className="sec-list">{(plans ?? []).length === 0 && <EmptyState icon="bi-journal" title="No LAP submissions" text="Employee action plans will appear here after training." />}{(plans ?? []).map((plan) => <article className="sec-item" key={plan.id}><button type="button" onClick={() => setExpanded(expanded === plan.id ? null : plan.id)} style={{ width: '100%', padding: 0, border: 0, background: 'transparent', textAlign: 'left', cursor: 'pointer' }}><div className="sec-row"><div style={{ display: 'flex', alignItems: 'center', gap: '.65rem' }}><Initials name={plan.employee_name} /><div><div className="sec-title">{plan.employee_name}</div><div className="sec-muted">{plan.employee_id} · {plan.submitted_on || 'Draft'}</div></div></div><StatusPill tone={tone(plan.receipt_status)}>{plan.receipt_status}</StatusPill></div><div className="sec-title" style={{ marginTop: '.65rem' }}>{plan.training_title}</div><p className="sec-copy">{plan.implementation_summary}</p></button>{expanded === plan.id && <><div className="sec-item" style={{ marginTop: '.6rem', background: 'rgba(20,184,166,.035)' }}><div className="sec-muted">LEARNING OUTCOMES</div><p className="sec-copy">{plan.learning_outcomes || 'No learning outcomes recorded.'}</p></div><ReceiptForm plan={plan} /></>}</article>)}</div></Panel></div><SecretariatStyles /></AppLayout>;
}
