import { useForm, usePage } from '@inertiajs/react';
import { useState } from 'react';
import AppLayout from '@/Layouts/AppLayout';
import { EmptyState, Initials, PageHero, Panel, SecretariatStyles, StatCard, StatusPill } from '../Shared';

const toneFor = (status) => status === 'completed' ? 'success' : status === 'ongoing' ? 'info' : status === 'rejected' ? 'danger' : 'warning';

function ProcessForm({ application }) {
    const form = useForm({ status: application.status, process_remarks: application.process_remarks ?? '' });
    return <form onSubmit={(event) => { event.preventDefault(); form.patch(`/secretariat/applications/${application.id}`, { preserveScroll: true }); }} className="sec-form" style={{ marginTop: '.75rem', paddingTop: '.75rem', borderTop: '1px dashed var(--admin-border-strong)' }}><div className="sec-field"><label>Processing decision</label><select value={form.data.status} onChange={(event) => form.setData('status', event.target.value)}><option value="applied">Keep pending</option><option value="ongoing">Approve activity</option><option value="completed">Mark completed</option><option value="rejected">Reject request</option></select></div><div className="sec-field"><label>Remarks</label><textarea rows="3" value={form.data.process_remarks} onChange={(event) => form.setData('process_remarks', event.target.value)} placeholder="Processing notes or conditions" /></div><div className="sec-field full"><button className="sec-button" disabled={form.processing}><i className="bi bi-check2-square" />{form.processing ? 'Saving...' : 'Save decision'}</button></div></form>;
}

export default function Index({ applications }) {
    const { props } = usePage();
    const [filter, setFilter] = useState('all');
    const [expanded, setExpanded] = useState(null);
    const visible = (applications ?? []).filter((item) => filter === 'all' || item.status === filter);
    return <AppLayout title="Training Applications" description="Secretariat / Application Processing"><div className="sec-page"><PageHero kicker="APPLICATION INBOX" title="Receive, evaluate, and process requests." description="Review employee training application details, record Secretariat remarks, and move approved activities into active monitoring." href="/secretariat/training-monitor" action="View approved activities" icon="bi-activity" />{props?.flash?.success && <div className="sec-success"><i className="bi bi-check-circle-fill" />{props.flash.success}</div>}<section className="sec-stats"><StatCard label="All Requests" value={(applications ?? []).length} icon="bi-files" /><StatCard label="Pending" value={(applications ?? []).filter((item) => item.status === 'applied').length} icon="bi-hourglass" color="#facc15" /><StatCard label="Approved" value={(applications ?? []).filter((item) => item.status === 'ongoing').length} icon="bi-check-circle" color="#38bdf8" /><StatCard label="Completed" value={(applications ?? []).filter((item) => item.status === 'completed').length} icon="bi-patch-check" color="#34d399" /></section><Panel title="Employee Requests" subtitle="Actual submitted training applications" action={<select className="sec-pill" value={filter} onChange={(event) => setFilter(event.target.value)} style={{ outline: 0 }}><option value="all">All statuses</option><option value="applied">Pending</option><option value="ongoing">Approved</option><option value="completed">Completed</option><option value="rejected">Rejected</option></select>}><div className="sec-list">{visible.length === 0 && <EmptyState title="No matching requests" text="Change the filter or wait for employee applications." />}{visible.map((item) => <article className="sec-item" key={item.id}><button type="button" onClick={() => setExpanded(expanded === item.id ? null : item.id)} style={{ width: '100%', padding: 0, border: 0, background: 'transparent', textAlign: 'left', cursor: 'pointer' }}><div className="sec-row"><div style={{ display: 'flex', alignItems: 'center', gap: '.65rem' }}><Initials name={item.employee_name} /><div><div className="sec-title">{item.employee_name}</div><div className="sec-muted">{item.employee_id} · {item.office || 'Office unassigned'}</div></div></div><div style={{ display: 'flex', alignItems: 'center', gap: '.55rem' }}><StatusPill tone={toneFor(item.status)}>{item.status}</StatusPill><i className={`bi bi-chevron-${expanded === item.id ? 'up' : 'down'} sec-muted`} /></div></div><div className="sec-title" style={{ marginTop: '.65rem' }}>{item.training_title}</div><div className="sec-muted" style={{ marginTop: '.2rem' }}>{item.training_type} · {item.provider || 'Provider not specified'}</div></button>{expanded === item.id && <ProcessForm application={item} />}</article>)}</div></Panel></div><SecretariatStyles /></AppLayout>;
}
