import AppLayout from '@/layouts/AppLayout';
import { AdminStyles, EmptyState, PageHero, Panel, StatCard, StatusPill } from '../Shared';

const pretty = (key) => key.replaceAll('_', ' ').replace(/\b\w/g, (c) => c.toUpperCase());

export default function Index({ summary, roleBreakdown, officeBreakdown, lnaRecords, trainingRecords, lapRecords }) {
    return <AppLayout title="L&D Reports" description="System Administrator / Analytics"><div className="sys-page">
        <PageHero kicker="SYSTEM LEARNING INTELLIGENCE" title="A complete view of organization-wide L&D records." description="Review participation, assessment, training, and post-training data, then export the current administrative report when needed." href="/admin/settings/export" action="Export CSV report" icon="bi-download" />
        <section className="sys-stats">{Object.entries(summary ?? {}).map(([key,value], index) => <StatCard key={key} label={pretty(key)} value={value} icon={['bi-ui-checks-grid','bi-exclamation-diamond','bi-send-check','bi-box-arrow-up-right','bi-house-check','bi-person-check','bi-journal','bi-journal-check'][index] ?? 'bi-activity'} color={['#38bdf8','#fb923c','#fbbf24','#a78bfa','#60a5fa','#2dd4bf','#c084fc','#4ade80'][index]} />)}</section>
        <section className="sys-grid-2"><Panel title="Learning Participation" subtitle="Distinct employees by activity"><div className="sys-list">{(roleBreakdown ?? []).map((item) => <div className="sys-item sys-row" key={item.role}><span className="sys-copy" style={{ textTransform: 'capitalize' }}>{item.role}</span><strong className="sys-title">{item.count}</strong></div>)}</div></Panel><Panel title="Office Breakdown" subtitle="Training applications by office"><div className="sys-list">{(officeBreakdown ?? []).length === 0 && <EmptyState title="No office data" text="Office activity will appear here." />}{(officeBreakdown ?? []).map((item) => <div className="sys-item sys-row" key={item.office}><span className="sys-copy">{item.office}</span><strong className="sys-title">{item.count}</strong></div>)}</div></Panel></section>
        <Panel title="Latest LNA Evaluations" subtitle="Most recent organization-wide assessments"><div className="sys-table-wrap"><table className="sys-table"><thead><tr><th>Employee</th><th>Employee ID</th><th>Focus Area</th><th>Priority</th><th>Status</th></tr></thead><tbody>{(lnaRecords ?? []).map((item) => <tr key={item.id}><td><strong>{item.employee_name}</strong></td><td>{item.employee_id}</td><td>{item.focus_area}</td><td><StatusPill tone={item.priority_level === 'high' ? 'danger' : 'info'}>{item.priority_level}</StatusPill></td><td><StatusPill>{item.status}</StatusPill></td></tr>)}</tbody></table></div></Panel>
        <Panel title="Training Applications and Progress" subtitle="Current training pipeline"><div className="sys-table-wrap"><table className="sys-table"><thead><tr><th>Employee</th><th>Training</th><th>Type</th><th>Progress</th><th>Status</th></tr></thead><tbody>{(trainingRecords ?? []).map((item) => <tr key={item.id}><td><strong>{item.employee_name}</strong></td><td>{item.training_title}</td><td>{item.training_type}</td><td>{item.progress_percent}%</td><td><StatusPill tone={item.status === 'completed' ? 'success' : 'info'}>{item.status}{item.is_attended ? ' | Attended' : ''}</StatusPill></td></tr>)}</tbody></table></div></Panel>
        <Panel title="Learning Action Plan Submissions" subtitle="Post-training application records"><div className="sys-table-wrap"><table className="sys-table"><thead><tr><th>Employee</th><th>Employee ID</th><th>Training</th><th>Status</th><th>Submitted</th></tr></thead><tbody>{(lapRecords ?? []).map((item) => <tr key={item.id}><td><strong>{item.employee_name}</strong></td><td>{item.employee_id}</td><td>{item.training_title}</td><td><StatusPill tone={item.status === 'completed' ? 'success' : 'info'}>{item.status}</StatusPill></td><td>{item.submitted_on || '-'}</td></tr>)}</tbody></table></div></Panel>
    </div><AdminStyles /></AppLayout>;
}
