import { useForm, usePage } from '@inertiajs/react';
import AppLayout from '@/layouts/AppLayout';
import { HrdcStyles, PageHero, Panel } from '../Shared';

export default function Index({ profile }) {
    const { props } = usePage();
    const form = useForm({ name: profile?.name ?? '', email: profile?.email ?? '', address: profile?.address ?? '' });
    return <AppLayout title="HRDC Profile" description="HRDC / Council Account"><div className="hr-page"><PageHero kicker="COUNCIL IDENTITY" title="Keep the HRDC review profile current." description="Update council contact details while reviewing the organization assignment associated with plan and program approval decisions." href="/settings/security" action="Security settings" icon="bi-shield-lock" />{props?.flash?.success && <div className="hr-success"><i className="bi bi-check-circle-fill" />{props.flash.success}</div>}<section className="hr-grid-2"><Panel title="Assignment Overview" subtitle="System and organizational record"><div className="hr-list"><div className="hr-item"><div className="hr-muted">ACCOUNT NAME</div><div className="hr-title" style={{ marginTop: '.25rem' }}>{profile.name}</div></div><div className="hr-item"><div className="hr-muted">EMPLOYEE ID</div><div className="hr-title" style={{ marginTop: '.25rem' }}>{profile.employee_id || 'Not assigned'}</div></div><div className="hr-item"><div className="hr-muted">OFFICE / POSITION</div><div className="hr-title" style={{ marginTop: '.25rem' }}>{profile.office || 'Not assigned'} · {profile.position || 'HRDC Member'}</div></div></div></Panel><Panel title="Contact Information" subtitle="Editable HRDC account details"><form onSubmit={(event) => { event.preventDefault(); form.patch('/hrdc/profile', { preserveScroll: true }); }} className="hr-form"><div className="hr-field full"><label>Full name</label><input value={form.data.name} onChange={(event) => form.setData('name', event.target.value)} />{form.errors.name && <span className="hr-error">{form.errors.name}</span>}</div><div className="hr-field full"><label>Email address</label><input type="email" value={form.data.email} onChange={(event) => form.setData('email', event.target.value)} />{form.errors.email && <span className="hr-error">{form.errors.email}</span>}</div><div className="hr-field full"><label>Address</label><textarea rows="4" value={form.data.address} onChange={(event) => form.setData('address', event.target.value)} /></div><div className="hr-field"><label>Employee ID</label><input value={profile.employee_id || ''} disabled /></div><div className="hr-field"><label>Office</label><input value={profile.office || ''} disabled /></div><div className="hr-field full"><button className="hr-button" disabled={form.processing}><i className="bi bi-save" />{form.processing ? 'Saving...' : 'Save profile'}</button></div></form></Panel></section></div><HrdcStyles /></AppLayout>;
}
