import { useForm, usePage } from '@inertiajs/react';
import AppLayout from '@/layouts/AppLayout';
import { Initials, PageHero, Panel, SecretariatStyles } from '../Shared';

export default function Index({ profile }) {
    const { props } = usePage();
    const form = useForm({ name: profile?.name ?? '', email: profile?.email ?? '', address: profile?.address ?? '' });
    return <AppLayout title="Secretariat Profile" description="Secretariat / Account Profile"><div className="sec-page"><PageHero kicker="SECRETARIAT IDENTITY" title="Keep the learning operations profile current." description="Update Secretariat contact information while reviewing the organizational assignment used for official plan and report submissions." href="/settings/security" action="Security settings" icon="bi-shield-lock" />{props?.flash?.success && <div className="sec-success"><i className="bi bi-check-circle-fill" />{props.flash.success}</div>}<section className="sec-grid-2"><Panel title="Assignment Overview" subtitle="System and organizational record"><div style={{ display: 'flex', alignItems: 'center', gap: '.8rem', paddingBottom: '1rem', borderBottom: '1px solid var(--admin-border)' }}><Initials name={profile.name} /><div><div className="sec-title">{profile.name}</div><div className="sec-muted">{profile.position || 'L&D Secretariat'} · {profile.office || 'Office not assigned'}</div></div></div><div className="sec-list" style={{ marginTop: '.8rem' }}><div className="sec-item"><div className="sec-muted">EMPLOYEE ID</div><div className="sec-title" style={{ marginTop: '.25rem' }}>{profile.employee_id || 'Not assigned'}</div></div><div className="sec-item"><div className="sec-muted">OFFICE</div><div className="sec-title" style={{ marginTop: '.25rem' }}>{profile.office || 'Not assigned'}</div></div><div className="sec-item"><div className="sec-muted">POSITION</div><div className="sec-title" style={{ marginTop: '.25rem' }}>{profile.position || 'Not assigned'}</div></div></div></Panel><Panel title="Contact Information" subtitle="Editable account details"><form onSubmit={(event) => { event.preventDefault(); form.patch('/secretariat/profile', { preserveScroll: true }); }} className="sec-form"><div className="sec-field full"><label>Full name</label><input value={form.data.name} onChange={(event) => form.setData('name', event.target.value)} />{form.errors.name && <span className="sec-error">{form.errors.name}</span>}</div><div className="sec-field full"><label>Email address</label><input type="email" value={form.data.email} onChange={(event) => form.setData('email', event.target.value)} />{form.errors.email && <span className="sec-error">{form.errors.email}</span>}</div><div className="sec-field full"><label>Address</label><textarea rows="4" value={form.data.address} onChange={(event) => form.setData('address', event.target.value)} /></div><div className="sec-field"><label>Employee ID</label><input value={profile.employee_id || ''} disabled /></div><div className="sec-field"><label>Office</label><input value={profile.office || ''} disabled /></div><div className="sec-field full"><button className="sec-button" disabled={form.processing}><i className="bi bi-save" />{form.processing ? 'Saving...' : 'Save profile'}</button></div></form></Panel></section></div><SecretariatStyles /></AppLayout>;
}
