import { Link } from '@inertiajs/react';

export const panelStyle = { background: 'var(--admin-card)', border: '1px solid var(--admin-border-strong)', borderRadius: 18, boxShadow: 'var(--admin-shadow)' };

export function HrdcStyles() {
    return <style>{`
        .hr-page { display: grid; gap: 1rem; }.hr-hero { position: relative; overflow: hidden; display: flex; align-items: flex-end; justify-content: space-between; gap: 1.5rem; min-height: 160px; padding: 1.5rem 1.65rem; border: 1px solid rgba(16,185,129,.24); border-radius: 22px; background: radial-gradient(circle at 84% 12%, rgba(34,197,94,.2), transparent 32%), linear-gradient(125deg, rgba(15,23,42,.98), rgba(12,74,110,.9) 58%, rgba(6,78,59,.82)); box-shadow: var(--admin-shadow); }.hr-hero::after { content: ''; position: absolute; right: 13%; bottom: -95px; width: 215px; height: 215px; border: 1px solid rgba(255,255,255,.07); border-radius: 50%; box-shadow: 0 0 0 36px rgba(255,255,255,.022), 0 0 0 72px rgba(255,255,255,.012); }.hr-kicker { color: #6ee7b7; font-size: .66rem; font-weight: 800; letter-spacing: .16em; }.hr-hero h1 { margin: .42rem 0; color: #ecfdf5; font-family: Georgia, 'Times New Roman', serif; font-size: clamp(1.75rem, 4vw, 2.5rem); font-weight: 500; letter-spacing: -.035em; }.hr-hero p { max-width: 680px; margin: 0; color: #cbd5e1; font-size: .82rem; line-height: 1.65; }.hr-action { z-index: 1; display: inline-flex; align-items: center; justify-content: center; gap: .5rem; padding: .72rem .92rem; color: #d1fae5; border: 1px solid rgba(110,231,183,.25); border-radius: 12px; background: rgba(2,6,23,.42); text-decoration: none; font-size: .74rem; font-weight: 750; white-space: nowrap; }
        .hr-stats { display: grid; grid-template-columns: repeat(4, minmax(145px, 1fr)); gap: .8rem; }.hr-stat { display: flex; align-items: center; gap: .8rem; padding: .95rem 1rem; }.hr-stat-icon { display: grid; width: 40px; height: 40px; place-items: center; color: var(--stat-color); border: 1px solid color-mix(in srgb, var(--stat-color) 30%, transparent); border-radius: 12px; background: color-mix(in srgb, var(--stat-color) 10%, transparent); }.hr-stat div:last-child { display: grid; gap: .12rem; }.hr-stat span { color: var(--admin-text-muted); font-size: .68rem; }.hr-stat strong { color: var(--admin-text-primary); font-size: 1.35rem; }
        .hr-panel { padding: 1rem 1.1rem; }.hr-head { display: flex; align-items: center; justify-content: space-between; gap: 1rem; margin-bottom: .85rem; }.hr-head h2 { margin: 0; color: var(--admin-text-primary); font-size: .92rem; }.hr-head p { margin: .2rem 0 0; color: var(--admin-text-muted); font-size: .7rem; }.hr-grid-2 { display: grid; grid-template-columns: minmax(0, 1.2fr) minmax(280px, .8fr); gap: 1rem; }.hr-grid-3 { display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: .8rem; }
        .hr-list { display: grid; gap: .65rem; }.hr-item { padding: .82rem .9rem; border: 1px solid var(--admin-border); border-radius: 13px; background: rgba(16,185,129,.025); }.hr-row { display: flex; align-items: center; justify-content: space-between; gap: .8rem; }.hr-title { color: var(--admin-text-primary); font-size: .78rem; font-weight: 750; }.hr-muted { color: var(--admin-text-muted); font-size: .69rem; line-height: 1.5; }.hr-copy { color: var(--admin-text-secondary); font-size: .75rem; line-height: 1.6; }.hr-pill { display: inline-flex; align-items: center; width: fit-content; padding: .28rem .53rem; color: #7dd3fc; border: 1px solid rgba(56,189,248,.22); border-radius: 999px; background: rgba(56,189,248,.08); color-scheme: dark; font-size: .62rem; font-weight: 750; text-transform: capitalize; white-space: nowrap; }.hr-pill option { color: #e2e8f0; background: #0f172a; text-transform: capitalize; }.hr-pill[data-tone='success'] { color: #86efac; border-color: rgba(34,197,94,.22); background: rgba(34,197,94,.09); }.hr-pill[data-tone='warning'] { color: #fde047; border-color: rgba(250,204,21,.22); background: rgba(250,204,21,.08); }.hr-pill[data-tone='danger'] { color: #fca5a5; border-color: rgba(239,68,68,.22); background: rgba(239,68,68,.08); }
        .hr-progress { height: 8px; overflow: hidden; border-radius: 999px; background: rgba(148,163,184,.12); }.hr-progress > span { display: block; height: 100%; border-radius: inherit; background: linear-gradient(90deg, #0284c7, #10b981); }.hr-table-wrap { overflow-x: auto; }.hr-table { width: 100%; min-width: 740px; border-collapse: collapse; }.hr-table th { padding: .6rem .65rem; color: var(--admin-text-muted); font-size: .65rem; text-align: left; text-transform: uppercase; letter-spacing: .05em; }.hr-table td { padding: .75rem .65rem; color: var(--admin-text-secondary); border-top: 1px solid var(--admin-border); font-size: .73rem; }.hr-table td strong { color: var(--admin-text-primary); }
        .hr-form { display: grid; grid-template-columns: 1fr 1fr; gap: .75rem; }.hr-field { display: grid; gap: .34rem; }.hr-field.full { grid-column: 1 / -1; }.hr-field label { color: var(--admin-text-muted); font-size: .67rem; font-weight: 700; }.hr-field input, .hr-field textarea, .hr-field select { width: 100%; padding: .67rem .74rem; color: var(--admin-text-primary); border: 1px solid var(--admin-border-strong); border-radius: 11px; outline: none; background: var(--admin-bg-secondary); font: inherit; font-size: .74rem; }.hr-button { display: inline-flex; align-items: center; justify-content: center; gap: .43rem; padding: .67rem .9rem; color: #fff; border: 0; border-radius: 11px; background: linear-gradient(135deg, #0369a1, #059669); font-size: .72rem; font-weight: 800; cursor: pointer; text-decoration: none; }.hr-button.secondary { color: var(--admin-text-primary); border: 1px solid var(--admin-border-strong); background: var(--admin-bg-secondary); }.hr-button:disabled { opacity: .6; cursor: wait; }.hr-success { display: flex; align-items: center; gap: .5rem; padding: .72rem .85rem; color: #86efac; border: 1px solid rgba(34,197,94,.24); border-radius: 12px; background: rgba(34,197,94,.09); font-size: .74rem; }.hr-error { color: #fca5a5; font-size: .64rem; }.hr-empty { display: grid; min-height: 180px; place-items: center; align-content: center; gap: .35rem; color: var(--admin-text-muted); text-align: center; }.hr-empty i { color: #34d399; font-size: 1.7rem; }.hr-empty strong { color: var(--admin-text-primary); font-size: .8rem; }.hr-empty span { font-size: .68rem; }
        @media (max-width: 1050px) { .hr-stats { grid-template-columns: repeat(2, 1fr); }.hr-grid-2 { grid-template-columns: 1fr; }.hr-grid-3 { grid-template-columns: 1fr 1fr; } } @media (max-width: 700px) { .hr-hero { align-items: flex-start; flex-direction: column; }.hr-action { width: 100%; }.hr-head { align-items: flex-start; flex-direction: column; }.hr-grid-3, .hr-form { grid-template-columns: 1fr; }.hr-field.full { grid-column: auto; } } @media (max-width: 470px) { .hr-stats { grid-template-columns: 1fr; } }
    `}</style>;
}

export function PageHero({ kicker, title, description, href, action, icon = 'bi-arrow-right' }) { return <section className="hr-hero"><div><div className="hr-kicker">{kicker}</div><h1>{title}</h1><p>{description}</p></div>{href && <Link className="hr-action" href={href}><i className={`bi ${icon}`} />{action}</Link>}</section>; }
export function StatCard({ label, value, icon, color = '#34d399' }) { return <div className="hr-stat" style={{ ...panelStyle, '--stat-color': color }}><div className="hr-stat-icon"><i className={`bi ${icon}`} /></div><div><span>{label}</span><strong>{value}</strong></div></div>; }
export function Panel({ title, subtitle, action, children }) { return <section className="hr-panel" style={panelStyle}>{(title || action) && <div className="hr-head"><div><h2>{title}</h2>{subtitle && <p>{subtitle}</p>}</div>{action}</div>}{children}</section>; }
export function StatusPill({ children, tone = 'info' }) { return <span className="hr-pill" data-tone={tone}>{children}</span>; }
export function EmptyState({ icon = 'bi-inbox', title, text }) { return <div className="hr-empty"><i className={`bi ${icon}`} /><strong>{title}</strong><span>{text}</span></div>; }
