import { useForm, usePage } from '@inertiajs/react';
import { useState } from 'react';
import AppLayout from '@/Layouts/AppLayout';
import { EmptyState, HrdcStyles, PageHero, Panel, StatCard, StatusPill } from '../Shared';

const tone = (status) => status === 'approved' ? 'success' : status === 'disapproved' ? 'danger' : 'warning';

function DecisionForm({ program }) {
    const form = useForm({ status: program.status, review_remarks: program.review_remarks ?? '' });
    return <form onSubmit={(event) => { event.preventDefault(); form.patch(`/hrdc/program-approvals/${program.id}`, { preserveScroll: true }); }} className="hr-form" style={{ marginTop: '.75rem', paddingTop: '.75rem', borderTop: '1px dashed var(--admin-border-strong)' }}><div className="hr-field"><label>HRDC decision</label><select value={form.data.status} onChange={(event) => form.setData('status', event.target.value)}><option value="pending">Keep pending</option><option value="approved">Approve program</option><option value="disapproved">Disapprove program</option></select></div><div className="hr-field"><label>Review remarks {form.data.status === 'disapproved' ? '(required)' : '(optional)'}</label><textarea rows="3" value={form.data.review_remarks} onChange={(event) => form.setData('review_remarks', event.target.value)} placeholder="Record rationale, conditions, or required revisions." />{form.errors.review_remarks && <span className="hr-error">{form.errors.review_remarks}</span>}</div><div className="hr-field full"><button className="hr-button" disabled={form.processing}><i className="bi bi-save" />{form.processing ? 'Saving...' : 'Save HRDC decision'}</button></div></form>;
}

export default function Index({ programs }) {
    const { props } = usePage();
    const [filter, setFilter] = useState('all');
    const [expanded, setExpanded] = useState(null);
    const visible = (programs ?? []).filter((item) => filter === 'all' || item.status === filter);
    return <AppLayout title="Program Approvals" description="HRDC / Proposed Training Programs"><div className="hr-page"><PageHero kicker="PROGRAM DECISION BOARD" title="Authorize training that advances the plan." description="Evaluate each proposed training program, record an approval or disapproval decision, and maintain clear rationale for Secretariat implementation." href="/hrdc/ld-plans" action="Review source plans" icon="bi-journals" />{props?.flash?.success && <div className="hr-success"><i className="bi bi-check-circle-fill" />{props.flash.success}</div>}<section className="hr-stats"><StatCard label="All Programs" value={(programs ?? []).length} icon="bi-list-check" /><StatCard label="Pending" value={(programs ?? []).filter((item) => item.status === 'pending').length} icon="bi-hourglass" color="#facc15" /><StatCard label="Approved" value={(programs ?? []).filter((item) => item.status === 'approved').length} icon="bi-patch-check" color="#34d399" /><StatCard label="Disapproved" value={(programs ?? []).filter((item) => item.status === 'disapproved').length} icon="bi-x-octagon" color="#f87171" /></section><Panel title="Proposed Training Programs" subtitle="Program-level decisions from submitted L&D Plans" action={<select className="hr-pill" value={filter} onChange={(event) => setFilter(event.target.value)} style={{ outline: 0 }}><option value="all">All decisions</option><option value="pending">Pending</option><option value="approved">Approved</option><option value="disapproved">Disapproved</option></select>}><div className="hr-list">{visible.length === 0 && <EmptyState icon="bi-check2-circle" title="No matching programs" text="Change the filter or wait for a submitted L&D Plan." />}{visible.map((program) => <article className="hr-item" key={program.id}><button type="button" onClick={() => setExpanded(expanded === program.id ? null : program.id)} style={{ width: '100%', padding: 0, border: 0, background: 'transparent', textAlign: 'left', cursor: 'pointer' }}><div className="hr-row"><div><div className="hr-title">{program.title}</div><div className="hr-muted">{program.plan_title} · {program.planning_year}</div></div><div style={{ display: 'flex', alignItems: 'center', gap: '.55rem' }}><StatusPill tone={tone(program.status)}>{program.status}</StatusPill><i className={`bi bi-chevron-${expanded === program.id ? 'up' : 'down'} hr-muted`} /></div></div><div className="hr-muted" style={{ marginTop: '.4rem' }}>Submitted by {program.submitted_by}</div></button>{expanded === program.id && <DecisionForm program={program} />}</article>)}</div></Panel></div><HrdcStyles /></AppLayout>;
}
