import { Link } from '@inertiajs/react';
import AppLayout from '@/layouts/AppLayout';
import { EmptyState, HrdcStyles, PageHero, Panel, StatCard, StatusPill } from '../Shared';

const tone = (status) => status === 'approved' ? 'success' : status === 'disapproved' ? 'danger' : 'warning';

export default function Index({ summary, planResults }) {
    return <AppLayout title="HRDC Decision Reports" description="HRDC / Approval Analytics"><div className="hr-page"><PageHero kicker="COUNCIL DECISION REPORT" title="See the shape of approved development investment." description="Monitor plan receipt, program decisions, approval rate, and remaining review workload across Secretariat submissions." href="/hrdc/program-approvals" action="Continue program review" icon="bi-patch-check" /><section className="hr-stats"><StatCard label="Plans Received" value={summary?.plans_received ?? 0} icon="bi-inbox" /><StatCard label="Programs Reviewed" value={summary?.programs_reviewed ?? 0} icon="bi-clipboard-check" color="#38bdf8" /><StatCard label="Approved" value={summary?.approved ?? 0} icon="bi-patch-check" color="#34d399" /><StatCard label="Approval Rate" value={`${summary?.approval_rate ?? 0}%`} icon="bi-graph-up-arrow" color="#facc15" /></section><Panel title="Plan Decision Results" subtitle="Program outcomes grouped by submitted L&D Plan">{(planResults ?? []).length === 0 ? <EmptyState icon="bi-bar-chart" title="No decision records" text="Submitted plans and program decisions will appear here." /> : <div className="hr-list">{(planResults ?? []).map((plan) => { const decided = plan.approved + plan.disapproved; const progress = plan.total_programs ? Math.round((decided / plan.total_programs) * 100) : 0; return <div className="hr-item" key={plan.id}><div className="hr-row"><div><div className="hr-title">{plan.title}</div><div className="hr-muted">Planning year {plan.planning_year}</div></div><StatusPill tone={tone(plan.review_status)}>{plan.review_status}</StatusPill></div><div className="hr-grid-3" style={{ marginTop: '.7rem' }}><div><div className="hr-muted">APPROVED</div><strong className="hr-title">{plan.approved}</strong></div><div><div className="hr-muted">DISAPPROVED</div><strong className="hr-title">{plan.disapproved}</strong></div><div><div className="hr-muted">PENDING</div><strong className="hr-title">{plan.pending}</strong></div></div><div className="hr-row" style={{ marginTop: '.65rem' }}><span className="hr-muted">Decision completion</span><strong className="hr-title">{progress}%</strong></div><div className="hr-progress" style={{ marginTop: '.35rem' }}><span style={{ width: `${progress}%` }} /></div><Link href={`/hrdc/ld-plans/${plan.id}`} className="hr-button secondary" style={{ marginTop: '.7rem' }}>Open plan</Link></div>})}</div>}</Panel></div><HrdcStyles /></AppLayout>;
}
