import { Link } from '@inertiajs/react';
import AppLayout from '@/layouts/AppLayout';
import { EmployeeStyles, EmptyState, PageHero, Panel, StatusPill } from '../Shared';

export default function Index({ recommendations, notifications }) {
    return <AppLayout title="Training Recommendations" description="Employee / Predictive Analytics"><div className="emp-page">
        <PageHero kicker="AI-ASSISTED LNA ANALYTICS" title="Your skills gap and recommended training." description="Review the model-ranked skills-gap analysis and prescriptive training recommendations generated after supervisor review." href="/employee/training-applications" action="Apply for training" icon="bi-journal-arrow-up" />
        <section className="emp-grid-2">
            <Panel title="Training Notices" subtitle="Current reminders and required actions"><div className="emp-list">{(notifications ?? []).length === 0 && <EmptyState icon="bi-bell" title="No notices yet" text="Complete your LNA assessment to begin your learning path." />}{(notifications ?? []).map((item, index) => <div className="emp-item" key={`${item.title}-${index}`}><div className="emp-row"><StatusPill tone={item.type === 'warning' ? 'warning' : 'info'}>{item.title}</StatusPill><i className="bi bi-bell emp-muted" /></div><div className="emp-copy" style={{ marginTop: '.5rem' }}>{item.message}</div></div>)}</div></Panel>
            <Panel title="How Recommendations Work" subtitle="Current Logistic Regression analytics model"><div className="emp-list"><div className="emp-item"><div className="emp-title">1. Supervisor completes the review</div><div className="emp-copy">Your analytics remain hidden while the LNA is still waiting for supervisor evaluation.</div></div><div className="emp-item"><div className="emp-title">2. Predictive skills-gap analysis</div><div className="emp-copy">The model scores each assessed competency using employee and supervisor ratings, skill gaps, IPCR, and available employee profile data.</div></div><div className="emp-item"><div className="emp-title">3. Ranked training recommendation</div><div className="emp-copy">The system ranks development programs for the highest-probability competency gaps. Your supervisor remains the final validator.</div></div></div></Panel>
        </section>
        <Panel title="Supervisor-Generated Recommendations" subtitle="Model analytics generated after supervisor review"><div className="emp-grid-3">{(recommendations ?? []).length === 0 && <EmptyState icon="bi-lightbulb" title="No recommendations generated" text="Your supervisor must complete the LNA review first." />}{(recommendations ?? []).map((item) => <div className="emp-item" key={`${item.lna_id}-${item.prescriptive_training_recommendation}`}><div className="emp-row"><StatusPill>{item.track}</StatusPill><StatusPill tone={item.has_application ? 'success' : 'warning'}>{item.has_application ? 'Applied' : 'Available'}</StatusPill></div><div className="emp-muted" style={{ marginTop: '.65rem' }}>PREDICTIVE SKILLS GAP</div><div className="emp-copy" style={{ marginTop: '.25rem' }}>{item.predictive_skills_gap}</div><div className="emp-muted" style={{ marginTop: '.7rem' }}>MODEL CONFIDENCE</div><div className="emp-title" style={{ marginTop: '.25rem', fontSize: '.84rem' }}>{item.confidence_score == null ? 'Not available' : `${(Number(item.confidence_score) * 100).toFixed(1)}%`}</div><div className="emp-muted" style={{ marginTop: '.7rem' }}>PRESCRIPTIVE TRAINING RECOMMENDATION</div><div className="emp-title" style={{ marginTop: '.25rem', fontSize: '.84rem' }}>{item.prescriptive_training_recommendation}</div><div className="emp-muted" style={{ marginTop: '.35rem' }}>{item.provider} | {item.training_type} · {item.model_version || 'Static fallback'}</div><div className="emp-copy" style={{ marginTop: '.4rem' }}>{item.rationale}</div>{(item.ranked_recommendations ?? []).length > 1 && <div className="emp-list" style={{ marginTop: '.75rem' }}>{item.ranked_recommendations.slice(1).map((ranked) => <div className="emp-item" key={`${item.lna_id}-${ranked.rank}`}><div className="emp-row"><div className="emp-title">#{ranked.rank} {ranked.training_title}</div><StatusPill tone="info">{(Number(ranked.probability) * 100).toFixed(1)}%</StatusPill></div><div className="emp-muted" style={{ marginTop: '.25rem' }}>{ranked.competency_name}</div></div>)}</div>}{!item.has_application && <Link className="emp-button" style={{ marginTop: '.7rem' }} href="/employee/training-applications"><i className="bi bi-send" />Apply now</Link>}</div>)}</div></Panel>
    </div><EmployeeStyles /></AppLayout>;
}
