import { Link } from '@inertiajs/react';
import AppLayout from '@/Layouts/AppLayout';
import { EmployeeStyles, EmptyState, PageHero, Panel, StatusPill } from '../Shared';

export default function Index({ recommendations, notifications }) {
    return <AppLayout title="Training Recommendations" description="Employee / Predictive Analytics"><div className="emp-page">
        <PageHero kicker="PERSONALIZED LEARNING PATH" title="Training recommendations built around your needs." description="Review the static predictive recommendations generated from your LNA, then submit a training application when you are ready." href="/employee/training-applications" action="Apply for training" icon="bi-journal-arrow-up" />
        <section className="emp-grid-2">
            <Panel title="Training Notices" subtitle="Current reminders and required actions"><div className="emp-list">{(notifications ?? []).length === 0 && <EmptyState icon="bi-bell" title="No notices yet" text="Complete your LNA assessment to begin your learning path." />}{(notifications ?? []).map((item, index) => <div className="emp-item" key={`${item.title}-${index}`}><div className="emp-row"><StatusPill tone={item.type === 'warning' ? 'warning' : 'info'}>{item.title}</StatusPill><i className="bi bi-bell emp-muted" /></div><div className="emp-copy" style={{ marginTop: '.5rem' }}>{item.message}</div></div>)}</div></Panel>
            <Panel title="How Recommendations Work" subtitle="Current static analytics model"><div className="emp-list"><div className="emp-item"><div className="emp-title">1. Assessment context</div><div className="emp-copy">Your focus area, competency gap, and intervention are grouped into a development track.</div></div><div className="emp-item"><div className="emp-title">2. Skills-gap prescription</div><div className="emp-copy">A clear capability gap is assigned using the current rule-based mapping.</div></div><div className="emp-item"><div className="emp-title">3. Training prediction</div><div className="emp-copy">A matching program is suggested and remains available for application.</div></div></div></Panel>
        </section>
        <Panel title="Predicted Training Recommendations" subtitle="Programs matched to your prescribed skills gaps"><div className="emp-grid-3">{(recommendations ?? []).length === 0 && <EmptyState icon="bi-lightbulb" title="No recommendations generated" text="Submit an LNA assessment first." />}{(recommendations ?? []).map((item) => <div className="emp-item" key={`${item.lna_id}-${item.predicted_training_recommendation}`}><div className="emp-row"><StatusPill>{item.track}</StatusPill><StatusPill tone={item.has_application ? 'success' : 'warning'}>{item.has_application ? 'Applied' : 'Available'}</StatusPill></div><div className="emp-title" style={{ marginTop: '.65rem', fontSize: '.84rem' }}>{item.predicted_training_recommendation}</div><div className="emp-muted" style={{ marginTop: '.35rem' }}>{item.provider} | {item.training_type}</div><div className="emp-copy" style={{ marginTop: '.55rem' }}>{item.prescribed_skills_gap}</div><div className="emp-copy" style={{ marginTop: '.4rem' }}>{item.rationale}</div>{!item.has_application && <Link className="emp-button" style={{ marginTop: '.7rem' }} href="/employee/training-applications"><i className="bi bi-send" />Apply now</Link>}</div>)}</div></Panel>
    </div><EmployeeStyles /></AppLayout>;
}
