import { Link } from '@inertiajs/react';
import AppLayout from '@/Layouts/AppLayout';
import { EmptyState, HrdcStyles, PageHero, Panel, StatCard, StatusPill } from '../Shared';

const tone = (status) => status === 'approved' ? 'success' : status === 'disapproved' ? 'danger' : status === 'partially-approved' ? 'info' : 'warning';

export default function Index({ plans }) {
    return <AppLayout title="L&D Plan Inbox" description="HRDC / Secretariat Submissions"><div className="hr-page"><PageHero kicker="PLAN RECEIVING DESK" title="Receive the organization’s learning blueprint." description="Review submitted Learning and Development Plans from Secretariat, inspect objectives and budget assumptions, and open each plan for program-level decisions." href="/hrdc/program-approvals" action="Open program approvals" icon="bi-patch-check" /><section className="hr-stats"><StatCard label="Plans Received" value={(plans ?? []).length} icon="bi-inbox-fill" /><StatCard label="Pending" value={(plans ?? []).filter((item) => item.review_status === 'pending').length} icon="bi-hourglass" color="#facc15" /><StatCard label="Under Review" value={(plans ?? []).filter((item) => item.review_status === 'under-review').length} icon="bi-search" color="#38bdf8" /><StatCard label="Approved Plans" value={(plans ?? []).filter((item) => item.review_status === 'approved').length} icon="bi-patch-check" color="#34d399" /></section><Panel title="Submitted L&D Plans" subtitle="Actual plans submitted by Secretariat"><div className="hr-list">{(plans ?? []).length === 0 && <EmptyState icon="bi-journal-x" title="No submitted plans" text="Plans saved as submitted by Secretariat will appear here." />}{(plans ?? []).map((plan) => <Link href={`/hrdc/ld-plans/${plan.id}`} className="hr-item" style={{ textDecoration: 'none' }} key={plan.id}><div className="hr-row"><div><div className="hr-title">{plan.title}</div><div className="hr-muted">Planning year {plan.planning_year} · Submitted by {plan.submitted_by}</div></div><StatusPill tone={tone(plan.review_status)}>{plan.review_status}</StatusPill></div><p className="hr-copy">{plan.objectives}</p><div className="hr-grid-3"><div><div className="hr-muted">PROPOSED</div><strong className="hr-title">{plan.program_count}</strong></div><div><div className="hr-muted">APPROVED</div><strong className="hr-title">{plan.approved_count}</strong></div><div><div className="hr-muted">PENDING</div><strong className="hr-title">{plan.pending_count}</strong></div></div></Link>)}</div></Panel></div><HrdcStyles /></AppLayout>;
}
