import { useForm, usePage } from '@inertiajs/react';
import AppLayout from '@/layouts/AppLayout';
import { HrdcStyles, PageHero, Panel, StatusPill } from '../Shared';

const tone = (status) => status === 'approved' ? 'success' : status === 'disapproved' ? 'danger' : 'warning';

export default function Show({ plan, programs }) {
    const { props } = usePage();
    const receipt = useForm({ review_remarks: plan.review_remarks ?? '' });
    return <AppLayout title="L&D Plan Review" description="HRDC / L&D Plan Detail"><div className="hr-page"><PageHero kicker="PLAN REVIEW DOSSIER" title={plan.title} description="A complete view of Secretariat objectives, implementation notes, and the proposed programs requiring HRDC decisions." href="/hrdc/ld-plans" action="Back to plan inbox" icon="bi-arrow-left" />{props?.flash?.success && <div className="hr-success"><i className="bi bi-check-circle-fill" />{props.flash.success}</div>}<section className="hr-grid-2"><Panel title="Plan Overview" subtitle={`Planning year ${plan.planning_year}`}><div className="hr-list"><div className="hr-item"><div className="hr-row"><div><div className="hr-muted">SUBMITTED BY</div><div className="hr-title" style={{ marginTop: '.25rem' }}>{plan.submitted_by}</div></div><StatusPill tone={tone(plan.review_status)}>{plan.review_status}</StatusPill></div><div className="hr-muted" style={{ marginTop: '.4rem' }}>{plan.submitted_at}</div></div><div className="hr-item"><div className="hr-muted">STRATEGIC OBJECTIVES</div><p className="hr-copy">{plan.objectives}</p></div><div className="hr-item"><div className="hr-muted">BUDGET AND IMPLEMENTATION NOTES</div><p className="hr-copy">{plan.budget_notes || 'No budget notes provided.'}</p></div></div></Panel><Panel title="Receive Plan" subtitle="Acknowledge receipt and begin HRDC review"><form onSubmit={(event) => { event.preventDefault(); receipt.patch(`/hrdc/ld-plans/${plan.id}/receive`, { preserveScroll: true }); }} className="hr-form"><div className="hr-field full"><label>HRDC receiving remarks</label><textarea rows="6" value={receipt.data.review_remarks} onChange={(event) => receipt.setData('review_remarks', event.target.value)} placeholder="Record initial review notes or documentary requirements." /></div><div className="hr-field full"><button className="hr-button" disabled={receipt.processing}><i className="bi bi-inbox" />{receipt.processing ? 'Saving...' : 'Mark received / under review'}</button></div></form></Panel></section><Panel title="Proposed Training Programs" subtitle="Approve or disapprove each program in the centralized decision screen"><div className="hr-list">{(programs ?? []).map((program) => <div className="hr-item" key={program.id}><div className="hr-row"><div><div className="hr-title">{program.title}</div><div className="hr-muted" style={{ marginTop: '.2rem' }}>{program.reviewed_by ? `Reviewed by ${program.reviewed_by}` : 'Awaiting HRDC decision'}</div></div><StatusPill tone={tone(program.status)}>{program.status}</StatusPill></div>{program.review_remarks && <p className="hr-copy">{program.review_remarks}</p>}</div>)}</div><a className="hr-button" href="/hrdc/program-approvals" style={{ marginTop: '.8rem' }}><i className="bi bi-patch-check" />Open Program Approvals</a></Panel></div><HrdcStyles /></AppLayout>;
}
