import { Link } from '@inertiajs/react';

export const panelStyle = { background: 'var(--admin-card)', border: '1px solid var(--admin-border-strong)', borderRadius: 19, boxShadow: 'var(--admin-shadow)' };

export function AdminStyles() {
    return <style>{`
        .sys-page { display: grid; gap: 1rem; }.sys-hero { position: relative; overflow: hidden; display: flex; align-items: flex-end; justify-content: space-between; gap: 1.5rem; min-height: 158px; padding: 1.5rem 1.65rem; border: 1px solid rgba(251,191,36,.23); border-radius: 22px; background: radial-gradient(circle at 85% 8%, rgba(251,191,36,.2), transparent 31%), linear-gradient(125deg, rgba(30,58,138,.95), rgba(15,23,42,.98) 58%, rgba(120,53,15,.67)); box-shadow: var(--admin-shadow); }.sys-hero::after { content: ''; position: absolute; right: 12%; bottom: -94px; width: 215px; height: 215px; border: 1px solid rgba(255,255,255,.08); border-radius: 50%; box-shadow: 0 0 0 36px rgba(255,255,255,.022), 0 0 0 72px rgba(255,255,255,.012); }.sys-kicker { color: #fcd34d; font-size: .66rem; font-weight: 800; letter-spacing: .16em; }.sys-hero h1 { margin: .42rem 0; color: #fffbeb; font-family: Georgia, 'Times New Roman', serif; font-size: clamp(1.75rem,4vw,2.5rem); font-weight: 500; letter-spacing: -.035em; }.sys-hero p { max-width: 680px; margin: 0; color: #cbd5e1; font-size: .82rem; line-height: 1.65; }.sys-hero-action { z-index: 1; display: inline-flex; align-items: center; justify-content: center; gap: .5rem; padding: .72rem .92rem; color: #fef3c7; border: 1px solid rgba(252,211,77,.25); border-radius: 12px; background: rgba(2,6,23,.42); text-decoration: none; font-size: .74rem; font-weight: 750; white-space: nowrap; }
        .sys-stats { display: grid; grid-template-columns: repeat(3,minmax(145px,1fr)); gap: .8rem; }.sys-stat { display: flex; align-items: center; gap: .8rem; padding: .95rem 1rem; }.sys-stat-icon { display: grid; width: 40px; height: 40px; flex: 0 0 auto; place-items: center; color: var(--stat-color); border: 1px solid color-mix(in srgb,var(--stat-color) 30%,transparent); border-radius: 12px; background: color-mix(in srgb,var(--stat-color) 10%,transparent); }.sys-stat div:last-child { display:grid; gap:.12rem }.sys-stat span { color:var(--admin-text-muted); font-size:.68rem }.sys-stat strong { color:var(--admin-text-primary); font-size:1.35rem }
        .sys-panel { padding: 1rem 1.1rem; }.sys-panel-head { display:flex; align-items:center; justify-content:space-between; gap:1rem; margin-bottom:.85rem }.sys-panel-head h2 { margin:0; color:var(--admin-text-primary); font-size:.92rem }.sys-panel-head p { margin:.2rem 0 0; color:var(--admin-text-muted); font-size:.7rem }.sys-grid-2 { display:grid; grid-template-columns:minmax(0,1.2fr) minmax(280px,.8fr); gap:1rem }.sys-grid-3 { display:grid; grid-template-columns:repeat(3,minmax(0,1fr)); gap:.8rem }
        .sys-list { display:grid; gap:.65rem }.sys-item { padding:.82rem .9rem; border:1px solid var(--admin-border); border-radius:13px; background:rgba(251,191,36,.025) }.sys-row { display:flex; align-items:center; justify-content:space-between; gap:.8rem }.sys-title { color:var(--admin-text-primary); font-size:.78rem; font-weight:750 }.sys-muted { color:var(--admin-text-muted); font-size:.69rem; line-height:1.5 }.sys-copy { color:var(--admin-text-secondary); font-size:.75rem; line-height:1.6 }
        .sys-pill { display:inline-flex; align-items:center; width:fit-content; padding:.28rem .53rem; color:#fde68a; border:1px solid rgba(245,158,11,.22); border-radius:999px; background:rgba(245,158,11,.08); color-scheme:dark; font-size:.62rem; font-weight:750; text-transform:capitalize; white-space:nowrap }.sys-pill option { color:#e2e8f0; background:#0f172a }.sys-pill[data-tone='success'] { color:#86efac; border-color:rgba(34,197,94,.22); background:rgba(34,197,94,.09) }.sys-pill[data-tone='info'] { color:#7dd3fc; border-color:rgba(56,189,248,.22); background:rgba(56,189,248,.08) }.sys-pill[data-tone='danger'] { color:#fca5a5; border-color:rgba(239,68,68,.22); background:rgba(239,68,68,.08) }
        .sys-progress { height:8px; overflow:hidden; border-radius:999px; background:rgba(148,163,184,.12) }.sys-progress>span { display:block; height:100%; border-radius:inherit; background:linear-gradient(90deg,#2563eb,#f59e0b) }.sys-table-wrap { overflow-x:auto }.sys-table { width:100%; min-width:760px; border-collapse:collapse }.sys-table th { padding:.6rem .65rem; color:var(--admin-text-muted); font-size:.65rem; text-align:left; text-transform:uppercase; letter-spacing:.05em }.sys-table td { padding:.75rem .65rem; color:var(--admin-text-secondary); border-top:1px solid var(--admin-border); font-size:.73rem }.sys-table td strong { color:var(--admin-text-primary) }
        .sys-form { display:grid; grid-template-columns:1fr 1fr; gap:.75rem }.sys-field { display:grid; gap:.34rem }.sys-field.full { grid-column:1/-1 }.sys-field label { color:var(--admin-text-muted); font-size:.67rem; font-weight:700 }.sys-field input,.sys-field textarea,.sys-field select,.sys-input { width:100%; padding:.67rem .74rem; color:var(--admin-text-primary); border:1px solid var(--admin-border-strong); border-radius:11px; outline:none; background:var(--admin-bg-secondary); color-scheme:dark; font:inherit; font-size:.74rem }.sys-page select { color-scheme:dark }.sys-page option,.sys-field option,.sys-input option { color:#e2e8f0; background:#0f172a }.sys-field input:disabled { opacity:.65 }.sys-button { display:inline-flex; align-items:center; justify-content:center; gap:.43rem; padding:.67rem .9rem; color:#fff; border:0; border-radius:11px; background:linear-gradient(135deg,#2563eb,#b45309); font-size:.72rem; font-weight:800; cursor:pointer; text-decoration:none }.sys-button.secondary { color:var(--admin-text-primary); border:1px solid var(--admin-border-strong); background:var(--admin-bg-secondary) }.sys-button.danger { background:#b91c1c }.sys-button:disabled { opacity:.6; cursor:wait }.sys-search { display:flex; align-items:center; gap:.5rem; min-width:245px }.sys-success { display:flex; align-items:center; gap:.5rem; padding:.72rem .85rem; color:#86efac; border:1px solid rgba(34,197,94,.24); border-radius:12px; background:rgba(34,197,94,.09); font-size:.74rem }.sys-error { color:#fca5a5; font-size:.64rem }.sys-empty { display:grid; min-height:170px; place-items:center; align-content:center; gap:.35rem; color:var(--admin-text-muted); text-align:center }.sys-empty i { color:#fbbf24; font-size:1.7rem; opacity:.75 }.sys-empty strong { color:var(--admin-text-primary); font-size:.8rem }.sys-empty span { font-size:.68rem }.sys-link { color:#fcd34d; text-decoration:none; font-size:.7rem; font-weight:750 }.sys-modal { position:fixed; inset:0; z-index:1400; display:grid; place-items:center; padding:1rem; background:rgba(4,10,24,.72); backdrop-filter:blur(4px) }.sys-modal-card { width:100%; max-width:650px; max-height:90vh; overflow:auto; padding:1.2rem; border-radius:20px; background:var(--admin-card); border:1px solid var(--admin-border-strong); box-shadow:var(--admin-shadow) }
        @media(max-width:1050px){.sys-stats{grid-template-columns:repeat(2,1fr)}.sys-grid-2{grid-template-columns:1fr}.sys-grid-3{grid-template-columns:1fr 1fr}}@media(max-width:700px){.sys-hero{align-items:flex-start;flex-direction:column}.sys-hero-action{width:100%}.sys-panel-head{align-items:flex-start;flex-direction:column}.sys-search{width:100%;min-width:0}.sys-grid-3,.sys-form{grid-template-columns:1fr}.sys-field.full{grid-column:auto}}@media(max-width:470px){.sys-stats{grid-template-columns:1fr}}
    `}</style>;
}

export function PageHero({ kicker, title, description, href, action, icon = 'bi-arrow-right' }) {
    const actionContent = <><i className={`bi ${icon}`} />{action}</>;
    return <section className="sys-hero"><div><div className="sys-kicker">{kicker}</div><h1>{title}</h1><p>{description}</p></div>{href && (href.includes('/export') ? <a className="sys-hero-action" href={href}>{actionContent}</a> : <Link className="sys-hero-action" href={href}>{actionContent}</Link>)}</section>;
}
export function StatCard({ label, value, icon, color = '#fbbf24' }) { return <div className="sys-stat" style={{ ...panelStyle, '--stat-color': color }}><div className="sys-stat-icon"><i className={`bi ${icon}`} /></div><div><span>{label}</span><strong>{value}</strong></div></div>; }
export function Panel({ title, subtitle, action, children }) { return <section className="sys-panel" style={panelStyle}>{(title || action) && <div className="sys-panel-head"><div><h2>{title}</h2>{subtitle && <p>{subtitle}</p>}</div>{action}</div>}{children}</section>; }
export function StatusPill({ children, tone = 'info' }) { return <span className="sys-pill" data-tone={tone}>{children}</span>; }
export function EmptyState({ icon = 'bi-inbox', title, text }) { return <div className="sys-empty"><i className={`bi ${icon}`} /><strong>{title}</strong><span>{text}</span></div>; }
